### ISSUE TITLE
Little typo error (`extensio` instead of `extension`)

### ISSUE THREAD

**Issue by llaville** [remicollet/php-xpass#2]
Hello Remi,

While I browsed on different source of information about your package, I found a typo error on summary information.

I'm a bit confused because, it seems that do not came from source code itself !

- https://github.com/remicollet/php-xpass/blame/master/package.xml#L5

So when I've opened an issue on https://github.com/mlocati/pecl-info/issues/4 but @mlocati has right, the REST API returns wrong info

- https://pecl.php.net/rest/p/xpass/info.xml
- https://github.com/php/web-pecl/blob/master/src/Rest.php#L384

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns="http://pear.php.net/dtd/rest.package"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"    xsi:schemaLocation="http://pear.php.net/dtd/rest.package    http://pear.php.net/dtd/rest.package.xsd">
 <n>xpass</n>
 <c>pecl.php.net</c>
 <ca xlink:href="/rest/c/Encryption">Encryption</ca>
 <l>PHP-3.01</l>
 <s>Extended password extensio</s>
 <d>This extension provides password hashing algorithms used by Linux distributions,
using extended crypt library (libxcrypt).

* sha512 provided for legacy as used on some old distributions
* yescrypt used on modern distributions
</d>
 <r xlink:href="/rest/r/xpass"/>
</p>
```

Could you fix the PECL database contents ?

**Comment by remicollet** [comment]
Sorry, but there is nothing I can do here

* package.xml is OK
* https://pecl.php.net/package/xpass is also OK
